Repository pngwriter/pngwriter, pull requests merged in 2019-02, with the labels that each got.

#130 Added function to write PNG to a memory buffer.
  src/pngwriter.cc
  src/pngwriter.h
Labels: api-change, enhancement

#134 Refactor write_to_buffer()
  src/pngwriter.cc
  src/pngwriter.h
Labels: refactoring

#135 CMake: Honor _ROOT Env Hints
  CMakeLists.txt
  PNGwriterConfig.cmake.in
Labels: warning
